server:
  port: 80

spring:
  zipkin:
    base-url: http://192.168.200.100:9411/
    sender:
      type: web


  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"  #运行所有请求
            allowedMethods: "*"  #允许所有请求方式
            allowedHeaders: "*"  #允许所有请求头，包括json跨域
            allowCredentials: true  #允许带一些安全标志跨域  比如:Cookie




      routes:
        - id: product_route
          uri: lb://service-product
          predicates:
            - Path=/admin/product/**

        - id: user_route
          uri: lb://service-user
          predicates:
            - Path=/api/user/**


        - id: lock_test
          uri: lb://service-item
          predicates:
            - Path=/lock/native




        - id: web_all
          uri: lb://web-all
          predicates:
            - Host=**.gmall.com

app:
  auth:
    no-auth-url:
      - /css/**
      - /js/**
      - /img/**
    login-auth-url:
      - /order/**
    deny-url:
      - /api/inner/**
    login-page: http://passport.gmall.com/login.html