server:
  port: 80

spring:
  zipkin:
    base-url: http://192.168.200.100:9411/
    sender:
      type: web


  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"  #运行所有请求
            allowedMethods: "*"  #允许所有请求方式



      routes:
        - id: product_route
          uri: lb://service-product
          predicates:
            - Path=/admin/product/**